services:
  cache:
    image: valkey/valkey:latest
    container_name: cache
    hostname: cache
    ports:
      - 6379:6379
    networks:
      - nextjs_net

  web:
    build: .
    # image: nextjs-docker
    container_name: nextjs-web
    hostname: nextjs-web
    ports:
      - 3000:3000
    environment:
      - CACHE_URL=redis://cache:6379
      - CACHE_AVAILABLE=True
    depends_on:
      - cache
    networks:
      - nextjs_net

networks:
  nextjs_net:
    name: nextjs_net
